name: deepsleep
description: "A new Flutter project."
publish_to: "none"

version: 0.2.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

  intl: ^0.18.1
  http: ^1.4.0
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.2.1
  alarm: ^5.1.4
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true

  assets:
    - assets/sunrise.png
    - assets/day.png
    - assets/sunset.png
    - assets/night.png
    - assets/tent.png
    - assets/alarm.mp3
    - assets/shop.png
    - assets/items/campbag.png
    - assets/items/chair.png
    - assets/items/clock.png
    - assets/items/lamp.png
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digi7/digi7-filled.otf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./assets/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
