name: Release

on: [push]

jobs:
  build_android:
    runs-on: macos-latest
    name: Build android releases and push artifacts
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build xcarchive --no-codesign
      - run: zip -r ios_xcarchive.zip build/ios/archive/Runner.xcarchive/
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            ios_xcarchive.zip
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly Release $$'
          prerelease: true
          body: 'Nightly release'
          files: |
            build/app/outputs/flutter-apk/app-debug.apk
            ios_xcarchive.zip
