name: Release

on: [push]

jobs:
  build_android:
    runs-on: macos-latest
    name: Build android releases and push artifacts
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build xcarchive --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/ios/archive/Runner.xcarchive
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/ios/archive/Runner.xcarchive
