name: Release

on: [push]

jobs:
  build_android:
    needs: [publish]
    runs-on: macos-latest
    name: Build android releases and push artifacts
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build xcarchive --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/ios/archive/Runner.xcarchive
      - name: Create nightly release
        id: create_release
        uses: viperproject/create-nightly-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          release_name: Nightly Release
          keep_num: 0
          keep_tags: false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/ios/archive/Runner.xcarchive
